name: .NET Tests and Coverage

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Run Tests with Coverage
      run: >
        dotnet test --no-build --configuration Release
        /p:CollectCoverage=true
        /p:CoverletOutputFormat=cobertura
        /p:Threshold=80
        /p:ThresholdType=line

    - name: Upload Coverage Report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: '**/coverage.cobertura.xml'
