name: .NET Tests and Coverage

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore CalculatorLib.sln

    - name: Build
      run: dotnet build CalculatorLib.sln --no-restore --configuration Release

    - name: Run tests with coverage
      run: |
          dotnet test CalculatorLib.Tests \
            --no-build --configuration Release \
            /p:CollectCoverage=true \
            /p:CoverletOutputFormat=cobertura \
            /p:CoverletOutput=coverage/

    - name: Install ReportGenerator
      run: dotnet tool install -g dotnet-reportgenerator-globaltool

    - name: Generate HTML report
      run: |
          reportgenerator \
            -reports:CalculatorLib.Tests/coverage/coverage.cobertura.xml \
            -targetdir:coverage-report \
            -reporttypes:Html

    - name: Upload coverage report artifact
      uses: actions/upload-artifact@v4
      with:
        name: CoverageReport
        path: coverage-report
