name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Test with coverage
        run: |
          dotnet test CalculatorLib.Tests \
            --no-build \
            --configuration Release \
            /p:CollectCoverage=true \
            /p:CoverletOutput=coverage/ \
            /p:CoverletOutputFormat=cobertura

      - name: Install ReportGenerator tool
        run: dotnet tool install --global dotnet-reportgenerator-globaltool

      - name: Add .NET tools to PATH
        run: echo "${HOME}/.dotnet/tools" >> $GITHUB_PATH

      - name: Generate HTML coverage report
        run: |
          reportgenerator \
            -reports:CalculatorLib.Tests/bin/Release/net8.0/coverage/coverage.cobertura.xml \
            -targetdir:coverage-report \
            -reporttypes:Html

      - name: Upload HTML report artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage-report
