name: .NET Core CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build solution
      run: dotnet build --configuration Release

    - name: Test with coverage
      run: |
        dotnet test CalculatorLib.Tests \
          --configuration Release \
          /p:CollectCoverage=true \
          /p:CoverletOutput=coverage/ \
          /p:CoverletOutputFormat=cobertura \
          /p:ExcludeByAttribute=GeneratedCodeAttribute

    - name: Install ReportGenerator tool
      run: dotnet tool install --global dotnet-reportgenerator-globaltool

    - name: Add dotnet tools to PATH
      run: echo "${HOME}/.dotnet/tools" >> $GITHUB_PATH

    - name: Generate coverage report
      run: |
        reportgenerator \
          -reports:CalculatorLib.Tests/coverage/coverage.cobertura.xml \
          -targetdir:coverage-report \
          -reporttypes:Html

    - name: Upload coverage report artifact
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage-report
